// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Savings.API.Infrastructure;

#nullable disable

namespace Savings.API.Migrations
{
    [DbContext(typeof(SavingsContext))]
    partial class SavingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Savings.Model.Configuration", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CashWithdrawalCategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<short>("EndPeriodRecurrencyInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndPeriodRecurrencyType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Configuration");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CashWithdrawalCategoryID = 0L,
                            EndPeriodRecurrencyInterval = (short)1,
                            EndPeriodRecurrencyType = 2
                        });
                });

            modelBuilder.Entity("Savings.Model.FixedMoneyItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccumulateForBudget")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cash")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimelineWeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToVerify")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Work")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Date");

                    b.ToTable("FixedMoneyItems");
                });

            modelBuilder.Entity("Savings.Model.MaterializedMoneyItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cash")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EndPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EndPeriodCashCarry")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FixedMoneyItemID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Projection")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecurrentMoneyItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimelineWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Work")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Date");

                    b.HasIndex("EndPeriod");

                    b.ToTable("MaterializedMoneyItems");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Amount = 0m,
                            Cash = false,
                            Date = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            EndPeriod = true,
                            EndPeriodCashCarry = 0m,
                            IsRecurrent = false,
                            Projection = 0m,
                            TimelineWeight = 0,
                            Type = 0,
                            Work = false
                        });
                });

            modelBuilder.Entity("Savings.Model.MaterializedMoneySubitems", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaterializedMoneyItemID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Work")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("MaterializedMoneyItemID");

                    b.ToTable("MaterializedMoneySubitems");
                });

            modelBuilder.Entity("Savings.Model.MoneyCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MoneyCategories");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Description = "Food"
                        },
                        new
                        {
                            ID = 2L,
                            Description = "Restaurant"
                        },
                        new
                        {
                            ID = 3L,
                            Description = "Home"
                        },
                        new
                        {
                            ID = 4L,
                            Description = "Car"
                        },
                        new
                        {
                            ID = 5L,
                            Description = "Fun"
                        },
                        new
                        {
                            ID = 6L,
                            Description = "Bills"
                        },
                        new
                        {
                            ID = 7L,
                            Description = "Loan"
                        },
                        new
                        {
                            ID = 8L,
                            Description = "Subscriptions"
                        },
                        new
                        {
                            ID = 9L,
                            Description = "Beauty"
                        },
                        new
                        {
                            ID = 10L,
                            Description = "Clothes"
                        },
                        new
                        {
                            ID = 11L,
                            Description = "Vacation"
                        },
                        new
                        {
                            ID = 12L,
                            Description = "Public Transport"
                        },
                        new
                        {
                            ID = 13L,
                            Description = "Health"
                        },
                        new
                        {
                            ID = 14L,
                            Description = "Gift"
                        },
                        new
                        {
                            ID = 15L,
                            Description = "Culture"
                        },
                        new
                        {
                            ID = 16L,
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("Savings.Model.RecurrencyAdjustement", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecurrencyDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RecurrencyNewAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecurrencyNewDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecurrentMoneyItemID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RecurrentMoneyItemID");

                    b.ToTable("RecurrencyAdjustements");
                });

            modelBuilder.Entity("Savings.Model.RecurrentMoneyItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultCredit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurrencyInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecurrencyType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecurrentMoneyItemID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimelineWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Work")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("RecurrentMoneyItemID");

                    b.HasIndex("StartDate");

                    b.ToTable("RecurrentMoneyItems");
                });

            modelBuilder.Entity("Savings.Model.FixedMoneyItem", b =>
                {
                    b.HasOne("Savings.Model.MoneyCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Savings.Model.MaterializedMoneyItem", b =>
                {
                    b.HasOne("Savings.Model.MoneyCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Savings.Model.MaterializedMoneySubitems", b =>
                {
                    b.HasOne("Savings.Model.MoneyCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("Savings.Model.MaterializedMoneyItem", null)
                        .WithMany("Subitems")
                        .HasForeignKey("MaterializedMoneyItemID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Savings.Model.RecurrencyAdjustement", b =>
                {
                    b.HasOne("Savings.Model.RecurrentMoneyItem", null)
                        .WithMany("Adjustements")
                        .HasForeignKey("RecurrentMoneyItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Savings.Model.RecurrentMoneyItem", b =>
                {
                    b.HasOne("Savings.Model.MoneyCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("Savings.Model.RecurrentMoneyItem", null)
                        .WithMany("AssociatedItems")
                        .HasForeignKey("RecurrentMoneyItemID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Savings.Model.MaterializedMoneyItem", b =>
                {
                    b.Navigation("Subitems");
                });

            modelBuilder.Entity("Savings.Model.RecurrentMoneyItem", b =>
                {
                    b.Navigation("Adjustements");

                    b.Navigation("AssociatedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
